### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by joshualeond** [TidierOrg/TidierVest.jl#2]
I attempted installing on Julia `1.10.0-beta` as well as `1.9.2` but both fail with the following:

```
(jl_jykT0u) pkg> add https://github.com/TidierOrg/TidierVest.jl.git
    Updating git-repo `https://github.com/TidierOrg/TidierVest.jl.git`
ERROR: Could not parse compatibility version for dependency `julia`
```

I'm wondering if the `Manifest.toml` is causing this?

Thanks!

**Comment by kdpsingh** [comment]
I think it's because there aren't commas between the Julia versions listed in the Project.toml.

However, my initial thoughts would be the following (after ensuring it doesn't cause problems):

1. We should clean up the [compat] entries a bit. The way compat works, we don't need to list every single version of Julia. If we list "1.6", it's automatically compatible with future versions up to but not including 2.0 (see the rules for compat outlined here: https://pkgdocs.julialang.org/v1/compatibility/). Unless there is a problem with Julia 1.6, I would suggest we change the entry to "1.6" to be compatible with the remainder of Tidier.jl. Similarly, we should change DataFrames to just "1.5" (to be compatible with Tidier.jl) and HTML to "0.8, 1", which will give us compatibility with 0.9, 1.1, 1.2, 1.3, etc.

2. We should remove Manifest.toml from the GitHub repo and add it to the .gitignore.

I'm happy to put in a PR for any of this if you'd like, @jdiaz97.

**Comment by jdiaz97** [comment]
Hello @joshualeond, it should work now. It does on Julia 1.9

Sorry for the error, it was becuase of a few random mistakes on project.toml.
Thanks you @kdpsingh for the compatibility lesson, really useful.

**Comment by joshualeond** [comment]
I was able to install it on Julia `1.10`. Thanks to both of you! Looking forward to using this more in the future.

**Comment by jdiaz97** [comment]
Awesome!
